nelmio_api_doc:
    documentation:
        info:
            title: Monkey Travel API
            description: API for a travel agency
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
